service:
   #service-player: 'serviceLista'
   service-player: 'serviceListaDB'
   
# management port
management:
  server:
    address: 127.0.0.1   #LOCALHOST
    port: 8083           #LOCALHOST

server:
   port: 8083    #LOCALHOST
   name: 'spring-jpa-thymeleaf'

logging:
    level:
      root: 'INFO'
      #root: 'DEBUG'

#debug: 'false'   

spring:
   profiles:
      active: mysql
   security:
      user:
         name: 'enrico'
         password: 'capone'
         roles: 'admin'
   thymeleaf:
     cache: false
---

# ===============================
# = MYSQL
# ===============================   
spring:
   profiles: mysql
   jpa:
      hibernate:
         #ddl-auto: 'create'
         #ddl-auto: 'none'
         ddl-auto: validate
         naming-strategy: 'org.hibernate.cfg.ImprovedNamingStrategy'   # Naming strategy
      show-sql: 'true'       # Show or not log for each sql query
      database-platform: 'org.hibernate.dialect.MySQL5InnoDBDialect'
      generate-ddl: true
      properties:
         hibernate:
            dialect: 'org.hibernate.dialect.MySQL5Dialect'   # Allows Hibernate to generate SQL optimized for a particular DBMS       
   datasource:
      url: 'jdbc:mysql://localhost:3308/players?serverTimezone=GMT&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true'
      username: 'root'
      password: 'capone'
      driver-class-name: 'com.mysql.cj.jdbc.Driver'
      testWhileIdle: 'true'      # Keep the connection alive if idle for a long time (needed in production)
      validationQuery: 'SELECT 1'
---

# ===============================
# = H2
# ===============================   
spring:
   profiles: h2
   jpa:
      show-sql: 'true'       # Show or not log for each sql query
      database: h2
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true     
   datasource:
      url: jdbc:h2:mem:players  # h2 In memory database, per accedere avviare il consumer e dal browser digitare localhost:8080/h2-console
      driver-class-name: org.h2.Driver
      username: 'enrico'
      password: 'capone'
   h2:
      console:
         enabled: 'true'
